// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251124135844_SyncModel")]
    partial class SyncModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Auditoria", b =>
                {
                    b.Property<int>("Id_Aud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Aud"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Id_Lote_Per")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Pro_Per")
                        .HasColumnType("int");

                    b.Property<string>("Tipo_Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Usuario")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id_Aud");

                    b.HasIndex("Id_Lote_Per");

                    b.HasIndex("Id_Pro_Per");

                    b.ToTable("auditoria", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Cliente", b =>
                {
                    b.Property<int>("Id_Cli")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Cli"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Correo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Num_Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Tipo_Cliente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Tipo_Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id_Cli");

                    b.HasIndex("Num_Documento")
                        .IsUnique();

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("Core.Entities.DescuentoProducto", b =>
                {
                    b.Property<int>("Id_Desc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Desc"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Id_Pro_Per")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Porcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id_Desc");

                    b.HasIndex("Id_Pro_Per");

                    b.ToTable("descuentos_producto", (string)null);
                });

            modelBuilder.Entity("Core.Entities.DetalleFactura", b =>
                {
                    b.Property<int>("Id_Det_Fac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Det_Fac"));

                    b.Property<int>("Cantidad_Comprada")
                        .HasColumnType("int");

                    b.Property<int>("Id_Fac_Per")
                        .HasColumnType("int");

                    b.Property<int>("Id_Lote_Per")
                        .HasColumnType("int");

                    b.Property<int>("Id_Pro_Per")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio_Venta_Total")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("(`Cantidad_Comprada` * `Precio_Venta_Unit`)");

                    b.Property<decimal>("Precio_Venta_Unit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_Det_Fac");

                    b.HasIndex("Id_Fac_Per");

                    b.HasIndex("Id_Lote_Per");

                    b.HasIndex("Id_Pro_Per");

                    b.ToTable("detallesfactura", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Factura", b =>
                {
                    b.Property<int>("Id_Fac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Fac"));

                    b.Property<DateTime>("Fec_Fac")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("IVA_Fac")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Id_Cli_Per")
                        .HasColumnType("int");

                    b.Property<decimal?>("Tot_Fac_Con_IVA")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Tot_Fac_Sin_IVA")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id_Fac");

                    b.HasIndex("Id_Cli_Per");

                    b.ToTable("facturas", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Lote", b =>
                {
                    b.Property<int>("Id_Lote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Lote"));

                    b.Property<int>("Cantidad_Disponible")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad_Recibida")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fec_Ent")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Fec_Exp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Id_Pro_Per")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio_Lote")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("(`Cantidad_Recibida` * `Precio_Unitario`)");

                    b.Property<decimal>("Precio_Unitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_Lote");

                    b.HasIndex("Id_Pro_Per");

                    b.ToTable("lotes", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Precio", b =>
                {
                    b.Property<int>("Id_Precio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Precio"));

                    b.Property<DateTime>("Fecha_Actualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Id_Pro_Per")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<decimal>("Precio_Venta")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_Precio");

                    b.HasIndex("Id_Pro_Per");

                    b.ToTable("precios", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Producto", b =>
                {
                    b.Property<int>("Id_Pro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Pro"));

                    b.Property<string>("Imagen")
                        .HasColumnType("longtext");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Nom_Pro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Tip_Pro")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id_Pro");

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Usuario", b =>
                {
                    b.Property<int>("Id_Usu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Usu"));

                    b.Property<string>("Contrasena_Usu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nom_Usu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id_Usu");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Auditoria", b =>
                {
                    b.HasOne("Core.Entities.Lote", "Lote")
                        .WithMany("Auditorias")
                        .HasForeignKey("Id_Lote_Per")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Core.Entities.Producto", "Producto")
                        .WithMany("Auditorias")
                        .HasForeignKey("Id_Pro_Per")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Lote");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Core.Entities.DescuentoProducto", b =>
                {
                    b.HasOne("Core.Entities.Producto", "Producto")
                        .WithMany("Descuentos")
                        .HasForeignKey("Id_Pro_Per")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Core.Entities.DetalleFactura", b =>
                {
                    b.HasOne("Core.Entities.Factura", "Factura")
                        .WithMany("Detalles")
                        .HasForeignKey("Id_Fac_Per")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Lote", "Lote")
                        .WithMany("DetallesFactura")
                        .HasForeignKey("Id_Lote_Per")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Entities.Producto", "Producto")
                        .WithMany("DetallesFactura")
                        .HasForeignKey("Id_Pro_Per")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("Lote");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Core.Entities.Factura", b =>
                {
                    b.HasOne("Core.Entities.Cliente", "Cliente")
                        .WithMany("Facturas")
                        .HasForeignKey("Id_Cli_Per")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Core.Entities.Lote", b =>
                {
                    b.HasOne("Core.Entities.Producto", "Producto")
                        .WithMany("Lotes")
                        .HasForeignKey("Id_Pro_Per")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Core.Entities.Precio", b =>
                {
                    b.HasOne("Core.Entities.Producto", "Producto")
                        .WithMany("Precios")
                        .HasForeignKey("Id_Pro_Per")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Core.Entities.Cliente", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("Core.Entities.Factura", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Core.Entities.Lote", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("DetallesFactura");
                });

            modelBuilder.Entity("Core.Entities.Producto", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("Descuentos");

                    b.Navigation("DetallesFactura");

                    b.Navigation("Lotes");

                    b.Navigation("Precios");
                });
#pragma warning restore 612, 618
        }
    }
}
